# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('db_size_profiles_archive', models.IntegerField()),
                ('db_size_profiles_frontend', models.IntegerField()),
                ('db_size_individual', models.IntegerField()),
                ('db_size_location_raw', models.IntegerField()),
                ('db_size_location_parsed', models.IntegerField()),
                ('db_size_emails', models.IntegerField()),
                ('db_size_search_engine', models.IntegerField()),
                ('db_size_corporations', models.IntegerField()),
                ('db_size_technology', models.IntegerField()),
                ('db_size_websites_processed', models.IntegerField()),
                ('db_size_appended', models.IntegerField()),
                ('db_size_email_campaign', models.IntegerField()),
                ('db_size_email_campaign_marketing', models.IntegerField()),
                ('db_size_email_campaign_csuite', models.IntegerField()),
            ],
        ),
    ]
