# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-25 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180525_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsmodule',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_set', to='dashboard.Dashboard'),
        ),
    ]
