# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-25 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180525_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='modules_set_name',
            field=models.CharField(default='operations_modules', max_length=255),
            preserve_default=False,
        ),
    ]
